# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 100
  permalink: "/page/:num/"
  sort_field: date
  sort_reverse: true

comments: false

future: false
source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: "Tech Adventures in Business Central | AL Development & AI Solutions"
description: "Exploring Business Central, AL coding, and AI-driven ERP solutions for developers and businesses."
keywords: "tech, technology, blog, azure, devops, dynamics, nav, business central, d365, mvp, bc, AL"
url: "https://tine.staric.net"
baseurl: ""

url: "https://tine.staric.net" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

# google_analytics: UA-XXXXXXXX-X

# Author settings
author:
  name: Tine Starič
  title: "Tech Adventures in Business Central"
  job: Software Architect at Companial and a Microsoft MVP for Business Applications
  bio: "Homebrewer, not a hipster. <br>A Business Central enthusiast, with a passion for all things weird with AL."
  thumb: /images/author.jpg
  email: tine@staric.net
  url: https://tine.staric.net
  github: https://github.com/tinestaric
  twitter: https://twitter.com/TineStaric
  linkedin: https://linkedin.com/in/tstaric

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog
  - slug: presentations
    title: Presentations

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]

include: [ "/.well-known" ]